apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    helm:
      values: |
        replicas: 1
        persistence:
          enabled: true
          size: 10Gi
          accessModes:
          - ReadWriteOnce
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
          -  a8e564a4b8ed14f4e9d207a227cf77ed-1314344661.ca-central-1.elb.amazonaws.com
        grafana.ini:
          server:
            root_url:  a8e564a4b8ed14f4e9d207a227cf77ed-1314344661.ca-central-1.elb.amazonaws.com
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 512Mi
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
